# 应用服务 WEB 访问端口
server:
  port: 8099
#在application.properties/或者application.yml文件中没有添加数据库配置信息.
# spring:
#datasource:
#url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#username: root
#password: 123456
#driver-class-name: com.mysql.jdbc.Driver
spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ef_cloud?useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
      initial-size: 10
      min-idle: 10
      max-active: 20
      max-wait: 60000
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

# 原文链接：https://blog.csdn.net/renkai721/article/details/112257894

oss:
  enable: true
  provider: minio
  endpoint: http://192.168.10.5:9090
  access-key: minioadmin
  secret-key: minioadmin
  bucket: ceshi
  expire: 3600
  region: us-east-1
  object-dir-prefix: wayline


#下面这些内容是为了让MyBatis映射
##指定Mybatis的Mapper文件
#mybatis.mapper-locations=classpath:mappers/*xml
##指定Mybatis的实体目录
#mybatis.type-aliases-package=com.example.javaknowledge1.mybatis.entity

mybatis:
  mapper-locations: "classpath:mappers/*xml"
  type-aliases-package: "com.example.javaknowledge1.mybatis.entity"


file:
  path:
    windows: F:\Minio\NoMinio\idea_home\ # windows下路径
    linux: /Users/lhk/Desktop/zhzf/pic/ #  linux下路径
    common: /Users/lhk/Desktop/zhzf/pic/ #  通用路径
